In [126]:
#made by Yusuf İlteriş Kaan Günay
from sklearn.preprocessing import MinMaxScaler
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score, roc_curve, auc
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
import numpy as np
from sklearn.ensemble import RandomForestClassifier
import sklearn
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score, precision_score, recall_score, roc_curve, auc
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.ensemble import VotingClassifier, RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import SelectKBest, f_classif

In [99]:
#made by Yusuf İlteriş Kaan Günay
data = pd.read_excel('student.xlsx')

# Displaying the first few rows of the dataset to understand its structure
data.head()

Unnamed: 0    Id  Student_Age     Sex High_School_Type Scholarship  \
0           0  5001           21    Male            Other         50%   
1           1  5002           20    Male            Other         50%   
2           2  5003           21    Male            State         50%   
3           3  5004           18  Female          Private         50%   
4           4  5005           22    Male          Private         50%   

  Additional_Work Sports_activity Transportation  Weekly_Study_Hours  \
0             Yes              No        Private                   0   
1             Yes              No        Private                   0   
2              No              No        Private                   2   
3             Yes              No            Bus                   2   
4              No              No            Bus                  12   

  Attendance Reading Notes Listening_in_Class Project_work Grade  
0     Always     Yes   Yes                 No           No    AA  
1     Always     Yes    No                Yes          Yes    AA  
2      Never      No    No                 No          Yes    AA  
3     Always      No   Yes                 No           No    AA  
4     Always     Yes    No                Yes          Yes    AA

In [100]:
#made by Yusuf İlteriş Kaan Günay
# Calculating descriptive statistics for the dataset
descriptive_stats_before = data.describe(include='all')

# Checking for missing values
missing_values_before = data.isnull().sum()

descriptive_stats_before, missing_values_before


(        Unnamed: 0           Id  Student_Age   Sex High_School_Type  \
 count   145.000000   145.000000   145.000000   145              145   
 unique         NaN          NaN          NaN     2                3   
 top            NaN          NaN          NaN  Male            State   
 freq           NaN          NaN          NaN    87              103   
 mean     72.000000  5073.000000    19.682759   NaN              NaN   
 std      42.001984    42.001984     1.992010   NaN              NaN   
 min       0.000000  5001.000000    18.000000   NaN              NaN   
 25%      36.000000  5037.000000    18.000000   NaN              NaN   
 50%      72.000000  5073.000000    19.000000   NaN              NaN   
 75%     108.000000  5109.000000    21.000000   NaN              NaN   
 max     144.000000  5145.000000    26.000000   NaN              NaN   
 
        Scholarship Additional_Work Sports_activity Transportation  \
 count          145             145             145            1

In [101]:
#made by Yusuf İlteriş Kaan Günay & Sultan Melda İnat
# Selecting numerical columns for normalization
numerical_columns = ['Student_Age', 'Weekly_Study_Hours']

# Initializing the Min-Max Scaler
scaler = MinMaxScaler()

# Applying the scaler to the dataset
data[numerical_columns] = scaler.fit_transform(data[numerical_columns])

# Calculating descriptive statistics after normalization
descriptive_stats_after = data.describe()

descriptive_stats_after


Unnamed: 0           Id  Student_Age  Weekly_Study_Hours
count  145.000000   145.000000   145.000000          145.000000
mean    72.000000  5073.000000     0.210345            0.194253
std     42.001984    42.001984     0.249001            0.354106
min      0.000000  5001.000000     0.000000            0.000000
25%     36.000000  5037.000000     0.000000            0.000000
50%     72.000000  5073.000000     0.125000            0.000000
75%    108.000000  5109.000000     0.375000            0.166667
max    144.000000  5145.000000     1.000000            1.000000

In [102]:
#made by Yusuf İlteriş Kaan Günay & Sultan Melda İnat
#In this section, descriptive statistics of the data set were calculated after Min-Max normalization of the Student_Age and Weekly_Study_Hours columns was performed.

# selecting numerical columns for normalization
numerical_columns = ['Student_Age', 'Weekly_Study_Hours']

# initializing the Min-Max Scaler
scaler = MinMaxScaler()

# applying the scaler to the dataset
data[numerical_columns] = scaler.fit_transform(data[numerical_columns])

# calculating descriptive statistics after normalization
descriptive_stats_after = data.describe()


In [103]:
#made by Yusuf İlteriş Kaan Günay & Sultan Melda İnat
# encoding categorical columns
categorical_columns = data.select_dtypes(include=['object']).columns
label_encoders = {}

for column in categorical_columns:
    le = LabelEncoder()
    data[column] = le.fit_transform(data[column])
    label_encoders[column] = le

# Splitting the dataset into features (X) and target (y)
# Assuming 'Grade' as the target variable for this task
X = data.drop(['Grade'], axis=1)
y = data['Grade']

# Splitting the data into training and testing sets (75% train, 25% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

X_train.shape, X_test.shape, y_train.shape, y_test.shape


((108, 15), (37, 15), (108,), (37,))

In [104]:
# Step 5 Machine Learning Part

#made by Yusuf İlteriş Kaan Günay
# Choosing the Decision Tree Classifier as it is one of the simpler models
dt_classifier = DecisionTreeClassifier(random_state=42)

# Performing 10-fold cross-validation on the training data
cv_scores = cross_val_score(dt_classifier, X_train, y_train, cv=10)

# Calculating average cross-validation score
average_cv_score = np.mean(cv_scores)

average_cv_score


/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=10.
  warnings.warn(


0.3081818181818182

In [111]:
#made by Yusuf İlteriş Kaan Günay

# Training the decision tree classifier on the training set
dt_classifier.fit(X_train, y_train)

# Predicting the test set
y_pred = dt_classifier.predict(X_test)

# Calculating confusion matrix, accuracy, F1 score, and other metrics
conf_matrix = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average='weighted')

# Calculating average accuracy, precision, recall
avg_accuracy = cross_val_score(dt_classifier, X_train, y_train, cv=5).mean()
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')

# Generating ROC curve values
try:
    y_prob = dt_classifier.predict_proba(X_test)
    fpr, tpr, thresholds = roc_curve(y_test, y_prob[:, 1], pos_label=1)
    roc_auc = auc(fpr, tpr)
except ValueError:
    roc_auc = None
    fpr, tpr = [None], [None]

# Displaying all the metrics with headers
print("Confusion Matrix:\n", conf_matrix)
print("\nAccuracy:", accuracy)
print("F1 Score:", f1)
print("Average Accuracy:", avg_accuracy)
print("Precision:", precision)
print("Recall:", recall)

if roc_auc is not None:
    print("ROC AUC:", roc_auc)
    print("False Positive Rate:", fpr)
    print("True Positive Rate:", tpr)
else:
    print("ROC curve values not applicable for Decision Trees")

    # i. Comparison of training and test data:
# Evaluate model performance metrics (accuracy, precision, recall, F1 score) on both datasets to assess generalization.
# Analyze overfitting (high training accuracy, low test accuracy) or underfitting (poor performance on both).
# Compare confusion matrices to understand error distribution.
# If applicable, review ROC/AUC for insights on class discrimination in training vs. test data.



Confusion Matrix:
 [[2 3 1 0 1 0 0 1]
 [3 2 1 0 0 0 0 0]
 [2 1 2 0 0 0 0 1]
 [1 0 0 1 0 0 1 0]
 [0 1 1 0 1 0 0 0]
 [0 0 1 1 0 0 2 0]
 [0 0 1 0 0 0 1 0]
 [2 0 1 0 1 0 0 1]]

Accuracy: 0.2702702702702703
F1 Score: 0.2555374055374055
Average Accuracy: 0.3246753246753247
Precision: 0.2562419562419562
Recall: 0.2702702702702703
ROC AUC: 0.586021505376344
False Positive Rate: [0.         0.16129032 1.        ]
True Positive Rate: [0.         0.33333333 1.        ]


/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [112]:
# made by Sultan Melda İnat
model2 = RandomForestClassifier()

# Random Forest machine learning method is chosen
model = sklearn.ensemble.RandomForestClassifier()
# a. The Holdout Method
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)
# b. Apply 10-Fold Cross-Validation
cv_results = cross_val_score(model, X_train, y_train, cv=10, scoring='accuracy')
model = RandomForestClassifier()
# Display the results of cross-validation
print("Cross-Validation Results:")
print("Average Accuracy: {:.2f}%".format(cv_results.mean() * 100))
model.fit(X_train, y_train)
# Predictions on the test set
y_pred = model.predict(X_test)
# Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:")
print(conf_matrix)
# Accuracy
accuracy = accuracy_score(y_test, y_pred)
print("\nAccuracy: {:.2f}%".format(accuracy * 100))
# F1 Score
f1 = f1_score(y_test, y_pred, average='weighted')
print("\nF1 Score: {:.2f}".format(f1))
# Sultan Melda İnat
#c. After parameter optimization, use 75% of data for training
rf_classifier = RandomForestClassifier(n_estimators=100)
rf_classifier.fit(X_train, y_train)

# Use the remaining 25% for testing
y_pred = rf_classifier.predict(X_test)
!pip install sklearn.preprocessing
from sklearn.preprocessing import LabelBinarizer

# i. Results of test data
conf_matrix = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average='weighted')

# Convert multiclass labels to binary labels
lb = LabelBinarizer()
y_test_bin = lb.fit_transform(y_test)
y_pred_bin = lb.transform(y_pred)

# Calculate ROC curve for binary labels
fpr, tpr, thresholds = roc_curve(y_test_bin.ravel(), y_pred_bin.ravel())
roc_auc = auc(fpr, tpr)

# Present results of test data
print("\nResults of test data:")
print("Confusion Matrix:\n", conf_matrix)
print("Accuracy: {:.2f}%".format(accuracy * 100))
print("F1 Score: {:.2f}".format(f1))
print("ROC AUC: {:.2f}".format(roc_auc))


# i. Comparison of training and test data

# -In terms of confusion matrices, In step C, seems to have slightly better results in some categories (e.g., higher values in the diagonal elements).
# -Accuracy and F1 Score in step C are also slightly higher than in step B.
#  *As a result, it is seen that step B has slightly better performance compared to step C.




/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=10.
  warnings.warn(


Cross-Validation Results:
Average Accuracy: 34.45%

Confusion Matrix:
[[3 2 0 0 1 0 1 1]
 [4 1 1 0 0 0 0 0]
 [3 1 1 1 0 0 0 0]
 [1 0 0 0 0 1 1 0]
 [0 1 0 0 2 0 0 0]
 [0 1 1 0 0 0 2 0]
 [0 0 0 0 0 0 2 0]
 [4 0 0 0 0 0 0 1]]

Accuracy: 27.03%

F1 Score: 0.24
ERROR: Could not find a version that satisfies the requirement sklearn.preprocessing (from versions: none)
ERROR: No matching distribution found for sklearn.preprocessing

Results of test data:
Confusion Matrix:
 [[4 2 1 0 0 0 0 1]
 [4 1 1 0 0 0 0 0]
 [3 0 2 1 0 0 0 0]
 [1 0 1 0 0 0 1 0]
 [0 1 1 0 1 0 0 0]
 [0 1 1 0 0 0 2 0]
 [0 0 1 0 0 0 1 0]
 [4 0 0 0 0 0 0 1]]
Accuracy: 27.03%
F1 Score: 0.25
ROC AUC: 0.58


In [116]:
#Yunus Kerem Saçar

# Veri ölçeklendirme
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Veri setini eğitim ve test setlerine ayırma
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.3, random_state=42)

# Logistic Regression modeli oluşturma ve eğitme
logreg_model = LogisticRegression(max_iter=1000)  # max_iter artırıldı
logreg_model.fit(X_train, y_train)

# Tahmin ve doğruluk hesaplama
y_pred = logreg_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

# Karmaşıklık matrisi
conf_matrix = confusion_matrix(y_test, y_pred)
print(f"Confusion Matrix:\n{conf_matrix}")

# ROC Eğrisi (ikili sınıflandırma için)
if len(np.unique(y_test)) == 2:
    y_pred_proba = logreg_model.predict_proba(X_test)[:, 1]
    fpr, tpr, thresholds = roc_curve(y_test, y_pred_proba)
    roc_auc = auc(fpr, tpr)

    plt.figure(figsize=(10, 6))
    plt.plot(fpr, tpr, label=f'AUC = {roc_auc:.2f}')
    plt.plot([0, 1], [0, 1], linestyle='--')
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.title('ROC Curve')
    plt.legend()
    plt.show()

# Hiperparametre ayarlama (GridSearchCV ile)
param_grid = {'C': [0.001, 0.01, 0.1, 1, 10, 100]}
grid_search = GridSearchCV(logreg_model, param_grid, cv=10, scoring='accuracy')
grid_search.fit(X_train, y_train)

# En iyi hiperparametreler
best_params = grid_search.best_params_
print(f"Best Hyperparameters: {best_params}")

# Cross-validation ile model değerlendirme
best_logreg_model = grid_search.best_estimator_
cv_scores = cross_val_score(best_logreg_model, X_train, y_train, cv=10, scoring='accuracy')
print(f"Cross-Validation Accuracy: {np.mean(cv_scores):.4f} (± {np.std(cv_scores):.4f})")

# Test verileri için model değerlendirme
y_pred_test = best_logreg_model.predict(X_test)
accuracy_test = accuracy_score(y_test, y_pred_test)
print(f"Accuracy (Test Data): {accuracy_test:.4f}")

# Test verileri için ROC Eğrisi ve F1 Skoru (ikili sınıflandırma için)
if len(np.unique(y_test)) == 2:
    y_pred_proba_test = best_logreg_model.predict_proba(X_test)[:, 1]
    fpr_test, tpr_test, thresholds_test = roc_curve(y_test, y_pred_proba_test)
    roc_auc_test = auc(fpr_test, tpr_test)

    plt.figure(figsize=(10, 6))
    plt.plot(fpr_test, tpr_test, label=f'AUC (Test Data) = {roc_auc_test:.2f}')
    plt.plot([0, 1], [0, 1], linestyle='--')
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.title('ROC Curve (Test Data)')
    plt.legend()
    plt.show()

# F1 Skoru (Test verileri için)
f1_test = f1_score(y_test, y_pred_test, average='weighted')
print(f"F1 Score (Test Data): {f1_test:.4f}")

# Eğitim ve Test verileri karşılaştırması
print("\nComparison with Training Data:")
print(f"Accuracy (Training Data): {np.mean(cv_scores):.4f} (± {np.std(cv_scores):.4f})")
print(f"Accuracy (Test Data): {accuracy_test:.4f}")
print(f"F1 Score (Training Data): {f1_score(y_train, cross_val_predict(best_logreg_model, X_train, y_train, cv=10), average='weighted'):.4f}")
print(f"F1 Score (Test Data): {f1_test:.4f}")


Accuracy: 0.22727272727272727
Confusion Matrix:
[[2 2 0 1 2 1 1 1]
 [4 3 2 0 0 0 0 0]
 [1 1 2 1 1 0 0 0]
 [0 0 0 0 3 0 0 0]
 [0 1 1 0 0 1 0 0]
 [1 0 1 0 0 0 3 0]
 [0 0 1 0 0 0 2 0]
 [3 0 0 0 0 1 0 1]]


/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=10.
  warnings.warn(


Best Hyperparameters: {'C': 0.1}
Cross-Validation Accuracy: 0.3182 (± 0.1003)
Accuracy (Test Data): 0.2273
F1 Score (Test Data): 0.1960

Comparison with Training Data:
Accuracy (Training Data): 0.3182 (± 0.1003)
Accuracy (Test Data): 0.2273
F1 Score (Training Data): 0.2662
F1 Score (Test Data): 0.1960


/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=10.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=10.
  warnings.warn(


In [120]:
# K-Nearest Neighbors Classifier
# Mert Beşer
knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train, y_train)
knn_predictions = knn_model.predict(X_test)
knn_accuracy = accuracy_score(y_test, knn_predictions)
print("K-Nearest Neighbors Accuracy:", knn_accuracy)

K-Nearest Neighbors Accuracy: 0.25


In [122]:
#Hakan Baha Akıncı
# Convert the `Sex` column to a numeric type
data['Sex'] = data['Sex'].astype('category').cat.codes

# Assuming the last column is the target and the rest are features
X = data.iloc[:, :-1]
y = data.iloc[:, -1]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Naive Bayes Classifier
nb_model = GaussianNB()
nb_model.fit(X_train, y_train)
nb_predictions = nb_model.predict(X_test)
nb_accuracy = accuracy_score(y_test, nb_predictions)
print("Naive Bayes Accuracy:", nb_accuracy)


Naive Bayes Accuracy: 0.18181818181818182


In [125]:

# Yusuf İlteriş Kaan Günay, Sultan Melda İnat, Mert Beşer, Yunus Kerem Saçar

#TASK 6 ENSEMBLE LEARNING

# Create classifiers
nb_classifier = GaussianNB()
knn_classifier = KNeighborsClassifier()
dt_classifier = DecisionTreeClassifier()
rf_classifier = RandomForestClassifier()
lr_classifier = LogisticRegression()

# Fit the classifiers
# Assuming X_train, y_train are already defined
nb_classifier.fit(X_train, y_train)
knn_classifier.fit(X_train, y_train)
dt_classifier.fit(X_train, y_train)
rf_classifier.fit(X_train, y_train)
lr_classifier.fit(X_train, y_train)

# Create an ensemble of all five classifiers
ensemble = VotingClassifier(estimators=[
    ('naive_bayes', nb_classifier),
    ('knn', knn_classifier),
    ('decision_tree', dt_classifier),
    ('random_forest', rf_classifier),
    ('logistic_regression', lr_classifier)
], voting='hard')

# Fit the ensemble classifier
ensemble.fit(X_train, y_train)

# Evaluate the ensemble classifier
ensemble_accuracy = ensemble.score(X_test, y_test)
print("Ensemble Accuracy:", ensemble_accuracy)


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Ensemble Accuracy: 0.25


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [135]:
# Yusuf İlteriş Kaan Günay, Sultan Melda İnat, Mert Beşer, Yunus Kerem Saçar

#TASK 7

# Feature Selection
selector = SelectKBest(score_func=f_classif, k='all')  # Adjust 'k' based on your needs
X_train_selected = selector.fit_transform(X_train, y_train)
X_test_selected = selector.transform(X_test)

# Train and evaluate all models with selected features
models = {
    'LogisticRegression': LogisticRegression(),
    'KNeighborsClassifier': KNeighborsClassifier(),
    'DecisionTreeClassifier': DecisionTreeClassifier(),
    'RandomForestClassifier': RandomForestClassifier(),
    'GaussianNB': GaussianNB()
}

best_model_name = None
best_accuracy = 0

for name, model in models.items():
    model.fit(X_train_selected, y_train)
    y_pred = model.predict(X_test_selected)
    accuracy = accuracy_score(y_test, y_pred)
    print(f"{name} Accuracy with selected features: {accuracy}")

    # Update the best model if the current model performs better
    if accuracy > best_accuracy:
        best_accuracy = accuracy
        best_model_name = name

# Print the best model's name and accuracy
print(f"The best performing model is {best_model_name} with an accuracy of {best_accuracy:.4f}.")


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression Accuracy with selected features: 0.1590909090909091
KNeighborsClassifier Accuracy with selected features: 0.25
DecisionTreeClassifier Accuracy with selected features: 0.20454545454545456
RandomForestClassifier Accuracy with selected features: 0.2727272727272727
GaussianNB Accuracy with selected features: 0.18181818181818182
The best performing model is RandomForestClassifier with an accuracy of 0.2727.
